# Generated by Django 4.1.1 on 2022-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=150)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('course_number', models.PositiveIntegerField()),
                ('course_subject', models.CharField(max_length=5)),
                ('course_title', models.TextField(max_length=254)),
                ('course_units', models.PositiveIntegerField()),
            ],
        ),
    ]
